server:
  port: 12345
  tomcat:
    threads:
      max: 100
  servlet:
    session:
      timeout: 600 #设置会话超时时间,单位是秒

# 数据库配置
spring:
  application:
    name: cometpan
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cometpan?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      database: 0    # Redis数据库索引（默认为0）
      host: 127.0.0.1
      timeout: 0
      password:
      port: 6379
      jedis:
        pool:
          max-wait: 10000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-active: 20 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          min-idle: 0
      connect-timeout: 5000ms # 连接超时时间（毫秒）

# 配置mybatis实体和xml映射
mybatis:

  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: top.nomelin.cometpan.pojo
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  file:
    path: /logs

# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: true #pageNum 小于 1 时会查询第一页，pageSize 小于 1 时会查询全部数据，等。
  support-methods-arguments: true
  params: count=countSql

#ip: localhost

avatar:
  folder: ./avatar

upload:
  folder: ./DiskFiles
  chunks:
    timeout: 24 # redis的分片缓存过期时间，单位：小时
  buffer-size: 2048 # 合并分片时的内存缓冲区大小，单位：字节
